In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [1]:
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/shilpadevi1527/integrated-conversations-csv/integrated_conversations.csv

In [2]:
import pandas as pd

file_path = "/kaggle/input/datasets/shilpadevi1527/integrated-conversations-csv/integrated_conversations.csv"

df = pd.read_csv(file_path)

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset shape: (276172, 8)

Columns:
['dialogue_id', 'turn_id', 'speaker', 'utterance', 'source_dataset', 'original_id', 'source_label_raw', 'dialogue_origin']

/tmp/ipykernel_58/1601900615.py:5: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [3]:
print(df.head(10).to_string())

                        dialogue_id  turn_id    speaker                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        utterance    source_dataset                       original_id source_label_raw dialogue_origin
0  000573958699464e9de6493b5e182fab        0       user                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Prompt: I want you to be my personal mental health Al counselor. I am a 16 year old male, struggling with OCD. Let's have a counseling session. I want you to utilize evidence-based therapeutic techniques to guide me through my struggles and help me improve my mental health.  Remember we are having a chat -- don't overwhelm me with a lot of text and keep the conversation flowing. Input: "Hey there, I'm NAME_1"  HealthChat-LMSYS  000573958699464e9de6493b5e182fab              NaN   reconstructed
1  000573958699464e9de6493b5e182fab        1  assistant                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NAME_2, it's nice to meet you. I'm here to help you with your mental health, specifically with your OCD. Let's start by talking about what you're currently experiencing with your OCD. What are some of the thoughts or behaviors that are causing you distress?  HealthChat-LMSYS  000573958699464e9de6493b5e182fab              NaN   reconstructed
2  000573958699464e9de6493b5e182fab        2       user                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   I guess there's quite a few things. But I primarily struggle with cleanliness   HealthChat-LMSYS  000573958699464e9de6493b5e182fab              NaN   reconstructed
3  000573958699464e9de6493b5e182fab        3  assistant                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Okay, that's a common theme for many people with OCD. Can you tell me more about what you do to try and maintain cleanliness? Are there certain things or situations that trigger your OCD thoughts and behaviors?  HealthChat-LMSYS  000573958699464e9de6493b5e182fab              NaN   reconstructed
4  000573958699464e9de6493b5e182fab        4       user                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Yeah, for example today I worked out in the morning and wanted to wash my hands after. But I didn't feel like they were clean enough. So I rewashed them over 15 times over the span of an hour, until my skin was completely dry.  HealthChat-LMSYS  000573958699464e9de6493b5e182fab              NaN   reconstructed
5  000573958699464e9de6493b5e182fab        5  assistant                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           I see. It sounds like you're experiencing excessive hand-washing, which is a common symptom of OCD. It can be difficult to control these compulsions, but there are ways to manage them. One technique that may be helpful for you is called "stimulus control." It involves breaking the connection between the trigger and the compulsive behavior.\n\nFor example, you can set a timer for hand-washing and only wash your hands for a certain amount of time, or you can use a specific type of soap that you only use for washing your hands. By breaking the connection between the trigger (dirt or discomfort) and the compulsive behavior (excessive washing), you can gradually weaken the OCD symptoms.\n\nDo you think this technique might be helpful for you? Are there any other compulsions or thoughts that are causing you distress?  HealthChat-LMSYS  000573958699464e9de6493b5e182fab              NaN   reconstructed
6  000573958699464e9de6493b5e182fab        6       user                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               How do I motivate myself to do this? I see how it'd help, but I feel like I wouldn't be able to mentally handle it  HealthChat-LMSYS  000573958699464e9de6493b5e182fab              NaN   reconstructed
7  000573958699464e9de6493b5e182fab        7  assistant                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                It's understandable that it can be difficult to motivate yourself to change old habits and patterns, especially when they are deeply ingrained. But remember, you are not alone and many people have successfully managed their OCD with the help of evidence-based therapies.\n\nOne way to motivate yourself is to focus on the benefits of making changes. For example, by reducing your hand-washing, you may be able to save time, prevent skin irritation, and reduce your anxiety. It can also be helpful to set small, achievable goals for yourself and reward yourself when you meet them.\n\nAnother technique that may be helpful is called "cognitive restructuring." This involves identifying and challenging negative or distorted thoughts, such as the belief that you need to wash your hands a certain number of times to be clean. By challenging these thoughts and replacing them with more realistic and positive ones, you can reduce your anxiety and improve your overall well-being.\n\nWould you like to try these techniques and see if they can help you manage your OCD symptoms?  HealthChat-LMSYS  000573958699464e9de6493b5e182fab              NaN   reconstructed
8  000573958699464e9de6493b5e182fab        8       user                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Can you tell me a little more about how I can implement cognitive restructuring?  HealthChat-LMSYS  000573958699464e9de6493b5e182fab              NaN   reconstructed
9  000573958699464e9de6493b5e182fab        9  assistant  Sure, cognitive restructuring is a technique that can help you identify and challenge negative or distorted thoughts, and replace them with more positive and realistic ones. Here are some steps you can follow:\n\n1. Identify the negative thought or belief: The first step is to identify the negative thought or belief that's causing you distress. For example, you may believe that you need to wash your hands a certain number of times to be clean.\n2. Challenge the thought: Once you've identified the negative thought, the next step is to challenge it. Ask yourself if it's really true, or if there's any evidence to support it. In this case, you might ask yourself if washing your hands 15 times is really necessary to be clean.\n3. Replace the thought: Once you've challenged the negative thought, try to replace it with a more positive and realistic one. For example, you could remind yourself that washing your hands a few times is enough to keep them clean and healthy.\n4. Practice: Like any skill, cognitive restructuring takes practice. Try to focus on your thoughts and beliefs throughout the day, and try to challenge any negative or distorted thoughts you notice. Over time, you'll become better at identifying and changing these thoughts, which can help you reduce your anxiety and improve your overall well-being.\n\nRemember, it's important to be patient with yourself and not get discouraged if you don't see immediate results. Change takes time and practice, but with persistence, you can make progress and improve your mental health.  HealthChat-LMSYS  000573958699464e9de6493b5e182fab              NaN   reconstructed

In [4]:
print("\nSpeaker distribution:")
print(df["speaker"].value_counts())

print("\nSource distribution:")
print(df["source_dataset"].value_counts())

print("\nDialogue origin:")
print(df["dialogue_origin"].value_counts())

print("\nMissing values:")
print(df.isnull().sum())

Speaker distribution:
speaker
user         138086
assistant    138086
Name: count, dtype: int64

Source distribution:
source_dataset
MedDialog              224328
HealthChat-LMSYS        28614
HealthChat-WildChat     23230
Name: count, dtype: int64

Dialogue origin:
dialogue_origin
constructed      224328
reconstructed     51844
Name: count, dtype: int64

Missing values:
dialogue_id             0
turn_id                 0
speaker                 0
utterance             198
source_dataset          0
original_id             0
source_label_raw    51844
dialogue_origin         0
dtype: int64

In [5]:
missing_rows = df[df["utterance"].isna()]

print("Number of missing utterances:", len(missing_rows))
print("\nMissing utterances by speaker:")
print(missing_rows["speaker"].value_counts())

print("\nMissing utterances by source:")
print(missing_rows["source_dataset"].value_counts())

print("\nMissing utterance rows:")
print(missing_rows[
    ["dialogue_id", "turn_id", "speaker", "source_dataset", "original_id"]
].to_string(index=False))

Number of missing utterances: 198

Missing utterances by speaker:
speaker
assistant    149
user          49
Name: count, dtype: int64

Missing utterances by source:
source_dataset
HealthChat-LMSYS       149
HealthChat-WildChat     49
Name: count, dtype: int64

Missing utterance rows:
                     dialogue_id  turn_id   speaker      source_dataset                      original_id
00801e92edad4f9eba6d8558c284553d       11 assistant    HealthChat-LMSYS 00801e92edad4f9eba6d8558c284553d
0190c13200ac4db0bfcb1a278de1f1a2        7 assistant    HealthChat-LMSYS 0190c13200ac4db0bfcb1a278de1f1a2
0190c13200ac4db0bfcb1a278de1f1a2        9 assistant    HealthChat-LMSYS 0190c13200ac4db0bfcb1a278de1f1a2
0473eeb47eb543a39216a3d728b36865       11 assistant    HealthChat-LMSYS 0473eeb47eb543a39216a3d728b36865
06ba3a0e654745d190448be10f7617e8        9 assistant    HealthChat-LMSYS 06ba3a0e654745d190448be10f7617e8
07326d11c659430c801e91bb0c24ff4a       15 assistant    HealthChat-LMSYS 07326d11c659430c801e91bb0c24ff4a
0732f41ebbbf4de19573f2f64785e9ee       13 assistant    HealthChat-LMSYS 0732f41ebbbf4de19573f2f64785e9ee
077749bd4cdb4d50b1d1645c67b7c88f        5 assistant    HealthChat-LMSYS 077749bd4cdb4d50b1d1645c67b7c88f
077749bd4cdb4d50b1d1645c67b7c88f        9 assistant    HealthChat-LMSYS 077749bd4cdb4d50b1d1645c67b7c88f
077749bd4cdb4d50b1d1645c67b7c88f       11 assistant    HealthChat-LMSYS 077749bd4cdb4d50b1d1645c67b7c88f
077749bd4cdb4d50b1d1645c67b7c88f       13 assistant    HealthChat-LMSYS 077749bd4cdb4d50b1d1645c67b7c88f
077749bd4cdb4d50b1d1645c67b7c88f       15 assistant    HealthChat-LMSYS 077749bd4cdb4d50b1d1645c67b7c88f
077749bd4cdb4d50b1d1645c67b7c88f       17 assistant    HealthChat-LMSYS 077749bd4cdb4d50b1d1645c67b7c88f
077749bd4cdb4d50b1d1645c67b7c88f       19 assistant    HealthChat-LMSYS 077749bd4cdb4d50b1d1645c67b7c88f
07fdaea703574573bd86de7cdb48066e        9 assistant    HealthChat-LMSYS 07fdaea703574573bd86de7cdb48066e
08af95bb551b41638d3e6419d44ca48e        5 assistant    HealthChat-LMSYS 08af95bb551b41638d3e6419d44ca48e
0d6bb1e672d94f43beabb91815b1b445       17 assistant    HealthChat-LMSYS 0d6bb1e672d94f43beabb91815b1b445
0d8563edbfe3414381d07fa6f851b0a6       13 assistant    HealthChat-LMSYS 0d8563edbfe3414381d07fa6f851b0a6
0d8563edbfe3414381d07fa6f851b0a6       21 assistant    HealthChat-LMSYS 0d8563edbfe3414381d07fa6f851b0a6
0d8563edbfe3414381d07fa6f851b0a6       27 assistant    HealthChat-LMSYS 0d8563edbfe3414381d07fa6f851b0a6
1478b0451cb44d089dd4eb54d11a91d1        3 assistant    HealthChat-LMSYS 1478b0451cb44d089dd4eb54d11a91d1
15e13a20b0974cc8a8d292c36e30aed0        9 assistant    HealthChat-LMSYS 15e13a20b0974cc8a8d292c36e30aed0
1ab1a825dd4541beba88a3a2b957541a       11 assistant    HealthChat-LMSYS 1ab1a825dd4541beba88a3a2b957541a
1ab1a825dd4541beba88a3a2b957541a       13 assistant    HealthChat-LMSYS 1ab1a825dd4541beba88a3a2b957541a
1b967041a2f54546b011b27ac0684a7f        9 assistant    HealthChat-LMSYS 1b967041a2f54546b011b27ac0684a7f
1b967041a2f54546b011b27ac0684a7f       11 assistant    HealthChat-LMSYS 1b967041a2f54546b011b27ac0684a7f
1e24f63e9e6142b3ae6a9e7e2415ac08       21 assistant    HealthChat-LMSYS 1e24f63e9e6142b3ae6a9e7e2415ac08
1e24f63e9e6142b3ae6a9e7e2415ac08       23 assistant    HealthChat-LMSYS 1e24f63e9e6142b3ae6a9e7e2415ac08
200b6b0577ae407c9ab70e5eaef84077       23 assistant    HealthChat-LMSYS 200b6b0577ae407c9ab70e5eaef84077
200b6b0577ae407c9ab70e5eaef84077       25 assistant    HealthChat-LMSYS 200b6b0577ae407c9ab70e5eaef84077
212fe73db05c43768e69953e0612a5d2       11 assistant    HealthChat-LMSYS 212fe73db05c43768e69953e0612a5d2
2948348f7c6a436d96fa6d071f5fe9dd        9 assistant    HealthChat-LMSYS 2948348f7c6a436d96fa6d071f5fe9dd
2d2bd1bb73f04fba955661192cc29d3b       11 assistant    HealthChat-LMSYS 2d2bd1bb73f04fba955661192cc29d3b
368951a1bb314d78905e7500c95356a3       17 assistant    HealthChat-LMSYS 368951a1bb314d78905e7500c95356a3
3ad3dbddc99d4755a77970f851ddb23a       17 assistant    HealthChat-LMSYS 3ad3dbddc99d4755a77970f851ddb23a
3aefa22c37b74290b73f94936708eac6       13 assistant    HealthChat-LMSYS 3aefa22c37b74290b73f94936708eac6
3aefa22c37b74290b73f94936708eac6       15 assistant    HealthChat-LMSYS 3aefa22c37b74290b73f94936708eac6
40bd87ac544440b38ed9b54aa639b74f        5 assistant    HealthChat-LMSYS 40bd87ac544440b38ed9b54aa639b74f
40bd87ac544440b38ed9b54aa639b74f        7 assistant    HealthChat-LMSYS 40bd87ac544440b38ed9b54aa639b74f
4923839380a94431918174e275763ad2       11 assistant    HealthChat-LMSYS 4923839380a94431918174e275763ad2
4923839380a94431918174e275763ad2       13 assistant    HealthChat-LMSYS 4923839380a94431918174e275763ad2
4bbea26872a349d9a3799d5e6b5ee2ec       17 assistant    HealthChat-LMSYS 4bbea26872a349d9a3799d5e6b5ee2ec
4ebbb66ad5fd483ea9dec5cf13a0bbe7       17 assistant    HealthChat-LMSYS 4ebbb66ad5fd483ea9dec5cf13a0bbe7
52de8eeb0c8e452abd7bc8c96e946c6f       13 assistant    HealthChat-LMSYS 52de8eeb0c8e452abd7bc8c96e946c6f
52de8eeb0c8e452abd7bc8c96e946c6f       15 assistant    HealthChat-LMSYS 52de8eeb0c8e452abd7bc8c96e946c6f
52de8eeb0c8e452abd7bc8c96e946c6f       17 assistant    HealthChat-LMSYS 52de8eeb0c8e452abd7bc8c96e946c6f
55ee14fb32044e77b62981f97e6afb4e       11 assistant    HealthChat-LMSYS 55ee14fb32044e77b62981f97e6afb4e
55ee14fb32044e77b62981f97e6afb4e       13 assistant    HealthChat-LMSYS 55ee14fb32044e77b62981f97e6afb4e
55ee14fb32044e77b62981f97e6afb4e       15 assistant    HealthChat-LMSYS 55ee14fb32044e77b62981f97e6afb4e
5aad17ab3dcd4f73a4cd217f8b18f760       11 assistant    HealthChat-LMSYS 5aad17ab3dcd4f73a4cd217f8b18f760
5aad17ab3dcd4f73a4cd217f8b18f760       13 assistant    HealthChat-LMSYS 5aad17ab3dcd4f73a4cd217f8b18f760
5c1350bcf24f4ae198a3646e6f2635fa       11 assistant    HealthChat-LMSYS 5c1350bcf24f4ae198a3646e6f2635fa
5c1350bcf24f4ae198a3646e6f2635fa       13 assistant    HealthChat-LMSYS 5c1350bcf24f4ae198a3646e6f2635fa
5c78aec2a63942728fac273ba652fc38       11 assistant    HealthChat-LMSYS 5c78aec2a63942728fac273ba652fc38
5c78aec2a63942728fac273ba652fc38       13 assistant    HealthChat-LMSYS 5c78aec2a63942728fac273ba652fc38
5c7978818ecc489198cd0d35237dd386       11 assistant    HealthChat-LMSYS 5c7978818ecc489198cd0d35237dd386
633c23648b9d436f9a878f0b67325701       17 assistant    HealthChat-LMSYS 633c23648b9d436f9a878f0b67325701
633c23648b9d436f9a878f0b67325701       19 assistant    HealthChat-LMSYS 633c23648b9d436f9a878f0b67325701
633c23648b9d436f9a878f0b67325701       21 assistant    HealthChat-LMSYS 633c23648b9d436f9a878f0b67325701
633c23648b9d436f9a878f0b67325701       23 assistant    HealthChat-LMSYS 633c23648b9d436f9a878f0b67325701
634eaf3437674519b3ba91508cc1ddbc       13 assistant    HealthChat-LMSYS 634eaf3437674519b3ba91508cc1ddbc
641ed3b4085d47afa2ee4447bd7270f1       19 assistant    HealthChat-LMSYS 641ed3b4085d47afa2ee4447bd7270f1
65a92b243e5b47ad83df80576e9a3b17        3 assistant    HealthChat-LMSYS 65a92b243e5b47ad83df80576e9a3b17
6674c18cdc1f4361850ca53291f40bb7       17 assistant    HealthChat-LMSYS 6674c18cdc1f4361850ca53291f40bb7
6674c18cdc1f4361850ca53291f40bb7       19 assistant    HealthChat-LMSYS 6674c18cdc1f4361850ca53291f40bb7
6695f6823cf245bfb2e9d80908ba6e0c       13 assistant    HealthChat-LMSYS 6695f6823cf245bfb2e9d80908ba6e0c
6926e009b83b4a76a5bcd396624fd499       13 assistant    HealthChat-LMSYS 6926e009b83b4a76a5bcd396624fd499
6926e009b83b4a76a5bcd396624fd499       15 assistant    HealthChat-LMSYS 6926e009b83b4a76a5bcd396624fd499
6926e009b83b4a76a5bcd396624fd499       17 assistant    HealthChat-LMSYS 6926e009b83b4a76a5bcd396624fd499
6b546d667f87410bb16d5bcdf1ffa438       11 assistant    HealthChat-LMSYS 6b546d667f87410bb16d5bcdf1ffa438
6c3df6ccc0dd4a17bdbe465b8a0a171b       13 assistant    HealthChat-LMSYS 6c3df6ccc0dd4a17bdbe465b8a0a171b
6dbc00c4effa4d1faabdd8d783caf49c        9 assistant    HealthChat-LMSYS 6dbc00c4effa4d1faabdd8d783caf49c
71e400b930174e29b72d92f212e0a605       15 assistant    HealthChat-LMSYS 71e400b930174e29b72d92f212e0a605
74e1dd8577044b70b114ccda57ef7318       17 assistant    HealthChat-LMSYS 74e1dd8577044b70b114ccda57ef7318
7595cd13fc964c9a8073a8e3bd71293e       11 assistant    HealthChat-LMSYS 7595cd13fc964c9a8073a8e3bd71293e
776b8e413a924c08b38c583c98f2fe67       13 assistant    HealthChat-LMSYS 776b8e413a924c08b38c583c98f2fe67
7999611b2ce2493cb3c73256ac35d424       15 assistant    HealthChat-LMSYS 7999611b2ce2493cb3c73256ac35d424
7c9b2fb378134a3882354a711a5e8a67       11 assistant    HealthChat-LMSYS 7c9b2fb378134a3882354a711a5e8a67
7c9b2fb378134a3882354a711a5e8a67       13 assistant    HealthChat-LMSYS 7c9b2fb378134a3882354a711a5e8a67
7caa186d24a74371bd744400e3d29f10       11 assistant    HealthChat-LMSYS 7caa186d24a74371bd744400e3d29f10
7e92358ac14743f18008203c1c55be05        9 assistant    HealthChat-LMSYS 7e92358ac14743f18008203c1c55be05
85d8e3b8f50e454c876a14d1f7579d02        9 assistant    HealthChat-LMSYS 85d8e3b8f50e454c876a14d1f7579d02
85d8e3b8f50e454c876a14d1f7579d02       11 assistant    HealthChat-LMSYS 85d8e3b8f50e454c876a14d1f7579d02
85d8e3b8f50e454c876a14d1f7579d02       13 assistant    HealthChat-LMSYS 85d8e3b8f50e454c876a14d1f7579d02
8701f956857d491bb11e21cf786c2fb6       11 assistant    HealthChat-LMSYS 8701f956857d491bb11e21cf786c2fb6
8701f956857d491bb11e21cf786c2fb6       13 assistant    HealthChat-LMSYS 8701f956857d491bb11e21cf786c2fb6
8838e6d2d6e34de08892e2500e3cff92       15 assistant    HealthChat-LMSYS 8838e6d2d6e34de08892e2500e3cff92
8db30532713247238865c43d1b8fdaa4       21 assistant    HealthChat-LMSYS 8db30532713247238865c43d1b8fdaa4
90511689cf384b5898471a76c9bc2fd9       13 assistant    HealthChat-LMSYS 90511689cf384b5898471a76c9bc2fd9
9723b9ebf89d46cc9532fc4ea19ac88f       13 assistant    HealthChat-LMSYS 9723b9ebf89d46cc9532fc4ea19ac88f
9723b9ebf89d46cc9532fc4ea19ac88f       15 assistant    HealthChat-LMSYS 9723b9ebf89d46cc9532fc4ea19ac88f
9d51e2e3baea4b89890cb0687565af44        9 assistant    HealthChat-LMSYS 9d51e2e3baea4b89890cb0687565af44
9d51e2e3baea4b89890cb0687565af44       11 assistant    HealthChat-LMSYS 9d51e2e3baea4b89890cb0687565af44
9d72ee9ba1184ad9b5cf376df02966c7       13 assistant    HealthChat-LMSYS 9d72ee9ba1184ad9b5cf376df02966c7
a0f46e2f734e499a9e6a08aa1a9983fd       13 assistant    HealthChat-LMSYS a0f46e2f734e499a9e6a08aa1a9983fd
a0f46e2f734e499a9e6a08aa1a9983fd       15 assistant    HealthChat-LMSYS a0f46e2f734e499a9e6a08aa1a9983fd
a0f46e2f734e499a9e6a08aa1a9983fd       17 assistant    HealthChat-LMSYS a0f46e2f734e499a9e6a08aa1a9983fd
a148f00249ee401f9c5a632d986dfda1        5 assistant    HealthChat-LMSYS a148f00249ee401f9c5a632d986dfda1
a3298c69a5d4447795423e9bf83dc4fc        1 assistant    HealthChat-LMSYS a3298c69a5d4447795423e9bf83dc4fc
a6207979c855466084ca2d00a45fa9ed       19 assistant    HealthChat-LMSYS a6207979c855466084ca2d00a45fa9ed
aa28c54fb583413ba48dc9cad29fbf5f       11 assistant    HealthChat-LMSYS aa28c54fb583413ba48dc9cad29fbf5f
aa28c54fb583413ba48dc9cad29fbf5f       13 assistant    HealthChat-LMSYS aa28c54fb583413ba48dc9cad29fbf5f
abcaea8e33f3464e9c245a536028b9d8       13 assistant    HealthChat-LMSYS abcaea8e33f3464e9c245a536028b9d8
abdf53af4c1b4ce38a5e4dd46297700d       17 assistant    HealthChat-LMSYS abdf53af4c1b4ce38a5e4dd46297700d
abdf53af4c1b4ce38a5e4dd46297700d       19 assistant    HealthChat-LMSYS abdf53af4c1b4ce38a5e4dd46297700d
abdf53af4c1b4ce38a5e4dd46297700d       21 assistant    HealthChat-LMSYS abdf53af4c1b4ce38a5e4dd46297700d
abdf53af4c1b4ce38a5e4dd46297700d       23 assistant    HealthChat-LMSYS abdf53af4c1b4ce38a5e4dd46297700d
abdf53af4c1b4ce38a5e4dd46297700d       25 assistant    HealthChat-LMSYS abdf53af4c1b4ce38a5e4dd46297700d
ad5321707d4d45bd9d134b4a266b244d       13 assistant    HealthChat-LMSYS ad5321707d4d45bd9d134b4a266b244d
af0480cdd2d242f2a3506c3c8a70d99e       13 assistant    HealthChat-LMSYS af0480cdd2d242f2a3506c3c8a70d99e
af35e9fe1579419dafb2a9be71e00819       11 assistant    HealthChat-LMSYS af35e9fe1579419dafb2a9be71e00819
b1e56b33ddf041b4a996b3f4dbf99191       15 assistant    HealthChat-LMSYS b1e56b33ddf041b4a996b3f4dbf99191
bc1052977fce43079597c68b18574772        9 assistant    HealthChat-LMSYS bc1052977fce43079597c68b18574772
c891f7c3c45643fc87903abd4a519132       11 assistant    HealthChat-LMSYS c891f7c3c45643fc87903abd4a519132
c8f6773497f64fabad41d4b71d3de8d3       15 assistant    HealthChat-LMSYS c8f6773497f64fabad41d4b71d3de8d3
cd4b0ac610564c67b08256546ec5843e        9 assistant    HealthChat-LMSYS cd4b0ac610564c67b08256546ec5843e
cd4b0ac610564c67b08256546ec5843e       11 assistant    HealthChat-LMSYS cd4b0ac610564c67b08256546ec5843e
cdffa267679f4b6a9fb1a0fbfaab2307       15 assistant    HealthChat-LMSYS cdffa267679f4b6a9fb1a0fbfaab2307
d1d3e8e9674b4a95929c2e658ba8e1b7       15 assistant    HealthChat-LMSYS d1d3e8e9674b4a95929c2e658ba8e1b7
d78e03514d0a4ccc86f3f84e46348c9d        9 assistant    HealthChat-LMSYS d78e03514d0a4ccc86f3f84e46348c9d
d78e03514d0a4ccc86f3f84e46348c9d       11 assistant    HealthChat-LMSYS d78e03514d0a4ccc86f3f84e46348c9d
d99fd7b4be0c43e8a63bf0b8f845c3e8       11 assistant    HealthChat-LMSYS d99fd7b4be0c43e8a63bf0b8f845c3e8
dad5fd51bacd489ab1cfd0be833225b4       11 assistant    HealthChat-LMSYS dad5fd51bacd489ab1cfd0be833225b4
dad5fd51bacd489ab1cfd0be833225b4       13 assistant    HealthChat-LMSYS dad5fd51bacd489ab1cfd0be833225b4
db610ef9a7104484860961707a902ad5       13 assistant    HealthChat-LMSYS db610ef9a7104484860961707a902ad5
e116fbbdf8364f8989dd3cdcc8c67271       15 assistant    HealthChat-LMSYS e116fbbdf8364f8989dd3cdcc8c67271
e36c2bfad20d4f17b2fcc73e26a174aa       17 assistant    HealthChat-LMSYS e36c2bfad20d4f17b2fcc73e26a174aa
e5e7a8fb7f1e4e21a8f1f557bbe0df08        9 assistant    HealthChat-LMSYS e5e7a8fb7f1e4e21a8f1f557bbe0df08
e9ff5d3376614fbdbd34887b12da04fb        7 assistant    HealthChat-LMSYS e9ff5d3376614fbdbd34887b12da04fb
ec5cbcba41a84bc2bf4c0e7370151490       15 assistant    HealthChat-LMSYS ec5cbcba41a84bc2bf4c0e7370151490
ed4ac0e4d9d84fbfa4c6a18fba358f35       11 assistant    HealthChat-LMSYS ed4ac0e4d9d84fbfa4c6a18fba358f35
ef33bbe9322a408f9725ea9a5eb9dd89       15 assistant    HealthChat-LMSYS ef33bbe9322a408f9725ea9a5eb9dd89
ef33bbe9322a408f9725ea9a5eb9dd89       19 assistant    HealthChat-LMSYS ef33bbe9322a408f9725ea9a5eb9dd89
f0916d2aff5f4c8d921f2cda2db673e9       11 assistant    HealthChat-LMSYS f0916d2aff5f4c8d921f2cda2db673e9
f09b092e4b0f4eaebf85a16890d5c775       23 assistant    HealthChat-LMSYS f09b092e4b0f4eaebf85a16890d5c775
f09b092e4b0f4eaebf85a16890d5c775       25 assistant    HealthChat-LMSYS f09b092e4b0f4eaebf85a16890d5c775
f14aad9b0d944c9db89943ad7c4a11f2       11 assistant    HealthChat-LMSYS f14aad9b0d944c9db89943ad7c4a11f2
f14aad9b0d944c9db89943ad7c4a11f2       13 assistant    HealthChat-LMSYS f14aad9b0d944c9db89943ad7c4a11f2
f14aad9b0d944c9db89943ad7c4a11f2       15 assistant    HealthChat-LMSYS f14aad9b0d944c9db89943ad7c4a11f2
f14aad9b0d944c9db89943ad7c4a11f2       17 assistant    HealthChat-LMSYS f14aad9b0d944c9db89943ad7c4a11f2
f49204ff9855423bad9b879dc4a08fd5       21 assistant    HealthChat-LMSYS f49204ff9855423bad9b879dc4a08fd5
f8d6c2a29fbf46538e9259d7caf58c30       15 assistant    HealthChat-LMSYS f8d6c2a29fbf46538e9259d7caf58c30
f8d6c2a29fbf46538e9259d7caf58c30       17 assistant    HealthChat-LMSYS f8d6c2a29fbf46538e9259d7caf58c30
fa16e49783a44302b68596881c494072       13 assistant    HealthChat-LMSYS fa16e49783a44302b68596881c494072
fa7e95cf141b425c939b7120e0f8a7e4       17 assistant    HealthChat-LMSYS fa7e95cf141b425c939b7120e0f8a7e4
fe5cd58c12fe426b80127b5767f3d736        7 assistant    HealthChat-LMSYS fe5cd58c12fe426b80127b5767f3d736
ff63c219b63c417d9f20d0d6663a2cfd       19 assistant    HealthChat-LMSYS ff63c219b63c417d9f20d0d6663a2cfd
ff63c219b63c417d9f20d0d6663a2cfd       21 assistant    HealthChat-LMSYS ff63c219b63c417d9f20d0d6663a2cfd
fff9eea71ad24df18d1fbfc7fb5ab3ad       11 assistant    HealthChat-LMSYS fff9eea71ad24df18d1fbfc7fb5ab3ad
013c533871805e16bda5c173f7719c0a        2      user HealthChat-WildChat 013c533871805e16bda5c173f7719c0a
04b4d6e1166144114cae072a7ad1b6a9        2      user HealthChat-WildChat 04b4d6e1166144114cae072a7ad1b6a9
066839ca3b3da4ec85915539029ff39f        6      user HealthChat-WildChat 066839ca3b3da4ec85915539029ff39f
112980b6fc0aeaa489a09e420121df26       10      user HealthChat-WildChat 112980b6fc0aeaa489a09e420121df26
11b17660560e437971927c56e6b9a47f        2      user HealthChat-WildChat 11b17660560e437971927c56e6b9a47f
14da9d75fd0b372f4f516f58d2470e8c       20      user HealthChat-WildChat 14da9d75fd0b372f4f516f58d2470e8c
167699f642344b0efd52180cb136d9e9        2      user HealthChat-WildChat 167699f642344b0efd52180cb136d9e9
3476f7956add347666be90b90ba8ad34        0      user HealthChat-WildChat 3476f7956add347666be90b90ba8ad34
38a73fab3f0ee33d4dbfcbf0b2066942        8      user HealthChat-WildChat 38a73fab3f0ee33d4dbfcbf0b2066942
391286fb902cf3ef3a2b766b295ee531        2      user HealthChat-WildChat 391286fb902cf3ef3a2b766b295ee531
498da521bce18ebb3b8d0215ae24e8bc        0      user HealthChat-WildChat 498da521bce18ebb3b8d0215ae24e8bc
4c8bc155f98b1d362621571b84cc5cb2        2      user HealthChat-WildChat 4c8bc155f98b1d362621571b84cc5cb2
59e973a4dc448c4767ec497346eb5b55        0      user HealthChat-WildChat 59e973a4dc448c4767ec497346eb5b55
59e973a4dc448c4767ec497346eb5b55        4      user HealthChat-WildChat 59e973a4dc448c4767ec497346eb5b55
59e973a4dc448c4767ec497346eb5b55        8      user HealthChat-WildChat 59e973a4dc448c4767ec497346eb5b55
5d2d39ee2e2f27818699578b61f4fc9f        8      user HealthChat-WildChat 5d2d39ee2e2f27818699578b61f4fc9f
61e5ed405550ff31ef07e787cc7f506b        2      user HealthChat-WildChat 61e5ed405550ff31ef07e787cc7f506b
6fb07e79e1677513d20af24be266e534       12      user HealthChat-WildChat 6fb07e79e1677513d20af24be266e534
710707371f3313a6c725523d4a9421b6        6      user HealthChat-WildChat 710707371f3313a6c725523d4a9421b6
803958cd5873b51ea8344c9d788934a0        4      user HealthChat-WildChat 803958cd5873b51ea8344c9d788934a0
80e824610befad9f3d89bf28949e4e36        0      user HealthChat-WildChat 80e824610befad9f3d89bf28949e4e36
80e824610befad9f3d89bf28949e4e36        2      user HealthChat-WildChat 80e824610befad9f3d89bf28949e4e36
82929f5a81b61557eb4678a3049cc9b3        0      user HealthChat-WildChat 82929f5a81b61557eb4678a3049cc9b3
86a94442ec6d2b41701bfba79e96938d       16      user HealthChat-WildChat 86a94442ec6d2b41701bfba79e96938d
88394beb39925fd6b6637d454a44388b        4      user HealthChat-WildChat 88394beb39925fd6b6637d454a44388b
9d824000d34cfc8a9e73dd17352d5d50       16      user HealthChat-WildChat 9d824000d34cfc8a9e73dd17352d5d50
9fe47f70f964ef8534d11876b705edbe        4      user HealthChat-WildChat 9fe47f70f964ef8534d11876b705edbe
a97c739d79d9143e1bba9d1c531c5987        8      user HealthChat-WildChat a97c739d79d9143e1bba9d1c531c5987
ad2d76c4970f5250c70d71257f86ae02       10      user HealthChat-WildChat ad2d76c4970f5250c70d71257f86ae02
af5686e1253657950eafd44e0be093a7        0      user HealthChat-WildChat af5686e1253657950eafd44e0be093a7
b302b2a9e578b477432d6dc88fb3a20b        0      user HealthChat-WildChat b302b2a9e578b477432d6dc88fb3a20b
b34fb6618c29f93c2fda78ba86e37882        2      user HealthChat-WildChat b34fb6618c29f93c2fda78ba86e37882
b8fa578905d01b1ffa0e58d9d2ef3f5c        0      user HealthChat-WildChat b8fa578905d01b1ffa0e58d9d2ef3f5c
b8fa578905d01b1ffa0e58d9d2ef3f5c        4      user HealthChat-WildChat b8fa578905d01b1ffa0e58d9d2ef3f5c
bbba1161a554fb2be30ffc983f8f961c        0      user HealthChat-WildChat bbba1161a554fb2be30ffc983f8f961c
bbba1161a554fb2be30ffc983f8f961c        4      user HealthChat-WildChat bbba1161a554fb2be30ffc983f8f961c
bd4cb067527cf104071772403fcb5d38        4      user HealthChat-WildChat bd4cb067527cf104071772403fcb5d38

In [6]:
# Conversations that contain at least one missing utterance
affected_dialogues = df.loc[
    df["utterance"].isna(),
    "dialogue_id"
].unique()

print("Number of affected conversations:", len(affected_dialogues))

# Show how many missing turns each affected conversation has
missing_by_dialogue = (
    df[df["dialogue_id"].isin(affected_dialogues)]
    .groupby(["dialogue_id", "source_dataset"])["utterance"]
    .apply(lambda x: x.isna().sum())
    .reset_index(name="missing_turns")
)

print("\nMissing turns per affected conversation:")
print(missing_by_dialogue.to_string(index=False))

Number of affected conversations: 139

Missing turns per affected conversation:
                     dialogue_id      source_dataset  missing_turns
00801e92edad4f9eba6d8558c284553d    HealthChat-LMSYS              1
013c533871805e16bda5c173f7719c0a HealthChat-WildChat              1
0190c13200ac4db0bfcb1a278de1f1a2    HealthChat-LMSYS              2
0473eeb47eb543a39216a3d728b36865    HealthChat-LMSYS              1
04b4d6e1166144114cae072a7ad1b6a9 HealthChat-WildChat              1
066839ca3b3da4ec85915539029ff39f HealthChat-WildChat              1
06ba3a0e654745d190448be10f7617e8    HealthChat-LMSYS              1
07326d11c659430c801e91bb0c24ff4a    HealthChat-LMSYS              1
0732f41ebbbf4de19573f2f64785e9ee    HealthChat-LMSYS              1
077749bd4cdb4d50b1d1645c67b7c88f    HealthChat-LMSYS              7
07fdaea703574573bd86de7cdb48066e    HealthChat-LMSYS              1
08af95bb551b41638d3e6419d44ca48e    HealthChat-LMSYS              1
0d6bb1e672d94f43beabb91815b1b445    HealthChat-LMSYS              1
0d8563edbfe3414381d07fa6f851b0a6    HealthChat-LMSYS              3
112980b6fc0aeaa489a09e420121df26 HealthChat-WildChat              1
11b17660560e437971927c56e6b9a47f HealthChat-WildChat              1
1478b0451cb44d089dd4eb54d11a91d1    HealthChat-LMSYS              1
14da9d75fd0b372f4f516f58d2470e8c HealthChat-WildChat              1
15e13a20b0974cc8a8d292c36e30aed0    HealthChat-LMSYS              1
167699f642344b0efd52180cb136d9e9 HealthChat-WildChat              1
1ab1a825dd4541beba88a3a2b957541a    HealthChat-LMSYS              2
1b967041a2f54546b011b27ac0684a7f    HealthChat-LMSYS              2
1e24f63e9e6142b3ae6a9e7e2415ac08    HealthChat-LMSYS              2
200b6b0577ae407c9ab70e5eaef84077    HealthChat-LMSYS              2
212fe73db05c43768e69953e0612a5d2    HealthChat-LMSYS              1
2948348f7c6a436d96fa6d071f5fe9dd    HealthChat-LMSYS              1
2d2bd1bb73f04fba955661192cc29d3b    HealthChat-LMSYS              1
3476f7956add347666be90b90ba8ad34 HealthChat-WildChat              1
368951a1bb314d78905e7500c95356a3    HealthChat-LMSYS              1
38a73fab3f0ee33d4dbfcbf0b2066942 HealthChat-WildChat              1
391286fb902cf3ef3a2b766b295ee531 HealthChat-WildChat              1
3ad3dbddc99d4755a77970f851ddb23a    HealthChat-LMSYS              1
3aefa22c37b74290b73f94936708eac6    HealthChat-LMSYS              2
40bd87ac544440b38ed9b54aa639b74f    HealthChat-LMSYS              2
4923839380a94431918174e275763ad2    HealthChat-LMSYS              2
498da521bce18ebb3b8d0215ae24e8bc HealthChat-WildChat              1
4bbea26872a349d9a3799d5e6b5ee2ec    HealthChat-LMSYS              1
4c8bc155f98b1d362621571b84cc5cb2 HealthChat-WildChat              1
4ebbb66ad5fd483ea9dec5cf13a0bbe7    HealthChat-LMSYS              1
52de8eeb0c8e452abd7bc8c96e946c6f    HealthChat-LMSYS              3
55ee14fb32044e77b62981f97e6afb4e    HealthChat-LMSYS              3
59e973a4dc448c4767ec497346eb5b55 HealthChat-WildChat              3
5aad17ab3dcd4f73a4cd217f8b18f760    HealthChat-LMSYS              2
5c1350bcf24f4ae198a3646e6f2635fa    HealthChat-LMSYS              2
5c78aec2a63942728fac273ba652fc38    HealthChat-LMSYS              2
5c7978818ecc489198cd0d35237dd386    HealthChat-LMSYS              1
5d2d39ee2e2f27818699578b61f4fc9f HealthChat-WildChat              1
61e5ed405550ff31ef07e787cc7f506b HealthChat-WildChat              1
633c23648b9d436f9a878f0b67325701    HealthChat-LMSYS              4
634eaf3437674519b3ba91508cc1ddbc    HealthChat-LMSYS              1
641ed3b4085d47afa2ee4447bd7270f1    HealthChat-LMSYS              1
65a92b243e5b47ad83df80576e9a3b17    HealthChat-LMSYS              1
6674c18cdc1f4361850ca53291f40bb7    HealthChat-LMSYS              2
6695f6823cf245bfb2e9d80908ba6e0c    HealthChat-LMSYS              1
6926e009b83b4a76a5bcd396624fd499    HealthChat-LMSYS              3
6b546d667f87410bb16d5bcdf1ffa438    HealthChat-LMSYS              1
6c3df6ccc0dd4a17bdbe465b8a0a171b    HealthChat-LMSYS              1
6dbc00c4effa4d1faabdd8d783caf49c    HealthChat-LMSYS              1
6fb07e79e1677513d20af24be266e534 HealthChat-WildChat              1
710707371f3313a6c725523d4a9421b6 HealthChat-WildChat              1
71e400b930174e29b72d92f212e0a605    HealthChat-LMSYS              1
74e1dd8577044b70b114ccda57ef7318    HealthChat-LMSYS              1
7595cd13fc964c9a8073a8e3bd71293e    HealthChat-LMSYS              1
776b8e413a924c08b38c583c98f2fe67    HealthChat-LMSYS              1
7999611b2ce2493cb3c73256ac35d424    HealthChat-LMSYS              1
7c9b2fb378134a3882354a711a5e8a67    HealthChat-LMSYS              2
7caa186d24a74371bd744400e3d29f10    HealthChat-LMSYS              1
7e92358ac14743f18008203c1c55be05    HealthChat-LMSYS              1
803958cd5873b51ea8344c9d788934a0 HealthChat-WildChat              1
80e824610befad9f3d89bf28949e4e36 HealthChat-WildChat              2
82929f5a81b61557eb4678a3049cc9b3 HealthChat-WildChat              1
85d8e3b8f50e454c876a14d1f7579d02    HealthChat-LMSYS              3
86a94442ec6d2b41701bfba79e96938d HealthChat-WildChat              1
8701f956857d491bb11e21cf786c2fb6    HealthChat-LMSYS              2
8838e6d2d6e34de08892e2500e3cff92    HealthChat-LMSYS              1
88394beb39925fd6b6637d454a44388b HealthChat-WildChat              1
8db30532713247238865c43d1b8fdaa4    HealthChat-LMSYS              1
90511689cf384b5898471a76c9bc2fd9    HealthChat-LMSYS              1
9723b9ebf89d46cc9532fc4ea19ac88f    HealthChat-LMSYS              2
9d51e2e3baea4b89890cb0687565af44    HealthChat-LMSYS              2
9d72ee9ba1184ad9b5cf376df02966c7    HealthChat-LMSYS              1
9d824000d34cfc8a9e73dd17352d5d50 HealthChat-WildChat              1
9fe47f70f964ef8534d11876b705edbe HealthChat-WildChat              1
a0f46e2f734e499a9e6a08aa1a9983fd    HealthChat-LMSYS              3
a148f00249ee401f9c5a632d986dfda1    HealthChat-LMSYS              1
a3298c69a5d4447795423e9bf83dc4fc    HealthChat-LMSYS              1
a6207979c855466084ca2d00a45fa9ed    HealthChat-LMSYS              1
a97c739d79d9143e1bba9d1c531c5987 HealthChat-WildChat              1
aa28c54fb583413ba48dc9cad29fbf5f    HealthChat-LMSYS              2
abcaea8e33f3464e9c245a536028b9d8    HealthChat-LMSYS              1
abdf53af4c1b4ce38a5e4dd46297700d    HealthChat-LMSYS              5
ad2d76c4970f5250c70d71257f86ae02 HealthChat-WildChat              1
ad5321707d4d45bd9d134b4a266b244d    HealthChat-LMSYS              1
af0480cdd2d242f2a3506c3c8a70d99e    HealthChat-LMSYS              1
af35e9fe1579419dafb2a9be71e00819    HealthChat-LMSYS              1
af5686e1253657950eafd44e0be093a7 HealthChat-WildChat              1
b1e56b33ddf041b4a996b3f4dbf99191    HealthChat-LMSYS              1
b302b2a9e578b477432d6dc88fb3a20b HealthChat-WildChat              1
b34fb6618c29f93c2fda78ba86e37882 HealthChat-WildChat              1
b8fa578905d01b1ffa0e58d9d2ef3f5c HealthChat-WildChat              2
bbba1161a554fb2be30ffc983f8f961c HealthChat-WildChat              2
bc1052977fce43079597c68b18574772    HealthChat-LMSYS              1
bd4cb067527cf104071772403fcb5d38 HealthChat-WildChat              1
c891f7c3c45643fc87903abd4a519132    HealthChat-LMSYS              1
c8f6773497f64fabad41d4b71d3de8d3    HealthChat-LMSYS              1
cd4b0ac610564c67b08256546ec5843e    HealthChat-LMSYS              2
cdffa267679f4b6a9fb1a0fbfaab2307    HealthChat-LMSYS              1
cee3350ea1a80c53d8db618ee5f478ac HealthChat-WildChat              2
cfcedce4791eedbd5f19793653373290 HealthChat-WildChat              1
d1d3e8e9674b4a95929c2e658ba8e1b7    HealthChat-LMSYS              1
d611bec3af1293e6805e728ff2f6d1cc HealthChat-WildChat              1
d78e03514d0a4ccc86f3f84e46348c9d    HealthChat-LMSYS              2
d99fd7b4be0c43e8a63bf0b8f845c3e8    HealthChat-LMSYS              1
dad5fd51bacd489ab1cfd0be833225b4    HealthChat-LMSYS              2
db19c1c906672c08fe4a465cfd9a1339 HealthChat-WildChat              1
db610ef9a7104484860961707a902ad5    HealthChat-LMSYS              1
e116fbbdf8364f8989dd3cdcc8c67271    HealthChat-LMSYS              1
e36c2bfad20d4f17b2fcc73e26a174aa    HealthChat-LMSYS              1
e5e7a8fb7f1e4e21a8f1f557bbe0df08    HealthChat-LMSYS              1
e9ff5d3376614fbdbd34887b12da04fb    HealthChat-LMSYS              1
ea4e12c3b39f9642ae0d4c8fd8607017 HealthChat-WildChat              1
ec5cbcba41a84bc2bf4c0e7370151490    HealthChat-LMSYS              1
ed4ac0e4d9d84fbfa4c6a18fba358f35    HealthChat-LMSYS              1
ef33bbe9322a408f9725ea9a5eb9dd89    HealthChat-LMSYS              2
f0916d2aff5f4c8d921f2cda2db673e9    HealthChat-LMSYS              1
f09b092e4b0f4eaebf85a16890d5c775    HealthChat-LMSYS              2
f14aad9b0d944c9db89943ad7c4a11f2    HealthChat-LMSYS              4
f22065d098ad2a328e87561b8eb763d8 HealthChat-WildChat              2
f33625a9a3c1d559a7d83a9351bbd171 HealthChat-WildChat              1
f49204ff9855423bad9b879dc4a08fd5    HealthChat-LMSYS              1
f724ba1ca6c0a24f0e0aa9e89b2af6a2 HealthChat-WildChat              1
f8d6c2a29fbf46538e9259d7caf58c30    HealthChat-LMSYS              2
f91b1d28e8c7d2b35be453222e37150d HealthChat-WildChat              1
fa16e49783a44302b68596881c494072    HealthChat-LMSYS              1
fa7e95cf141b425c939b7120e0f8a7e4    HealthChat-LMSYS              1
fcd2c171a15705af99c55c4bbb2e39ee HealthChat-WildChat              1
fe5cd58c12fe426b80127b5767f3d736    HealthChat-LMSYS              1
ff63c219b63c417d9f20d0d6663a2cfd    HealthChat-LMSYS              2
fff9eea71ad24df18d1fbfc7fb5ab3ad    HealthChat-LMSYS              1

In [7]:
# Show the first 5 affected conversations with their surrounding turns

for dialogue_id in affected_dialogues[:5]:
    print("\n" + "=" * 80)
    print("DIALOGUE:", dialogue_id)

    temp = df[df["dialogue_id"] == dialogue_id].sort_values("turn_id")

    print(temp[[
        "turn_id",
        "speaker",
        "utterance",
        "source_dataset"
    ]].to_string(index=False))

================================================================================
DIALOGUE: 00801e92edad4f9eba6d8558c284553d
 turn_id   speaker                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             utterance   source_dataset
       0      user                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Can a very activating antidepressant be a less suitable choice when anxiety is a great concern? Why? HealthChat-LMSYS
       1 assistant                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     The question you ask is quite complex, and there is no simple yes or no answer. It depends on many factors, such as the severity of the depression and anxiety, other health conditions, and the individual's response to different medications.\n\nGenerally, very activating antidepressants, such as SSRIs (selective serotonin reuptake inhibitors) and SNRIs (serotonin-norepinephrine reuptake inhibitors), can be helpful for both depression and anxiety. They are often used as first-line treatments for both conditions. However, they may not work for everyone, and some people may experience side effects such as insomnia, anxiety, and irritability.\n\nIf anxiety is a significant concern, it's important to consider the potential impact of these side effects. In some cases, a very activating antidepressant may increase anxiety, making it harder to cope with daily life. In these situations, a different type of antidepressant or a combination of medications may be more appropriate.\n\nIt's important to work with a healthcare professional to carefully evaluate the risks and benefits of different treatment options. They can help you make the best decision for your specific situation. HealthChat-LMSYS
       2      user                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                well, if fact, I make modafinil which is extremely activating probably HealthChat-LMSYS
       3 assistant                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Modafinil, also known by its brand name Provigil, is a prescription drug that is used to promote wakefulness and is often used to treat conditions such as narcolepsy, obstructive sleep apnea, and shift work sleep disorder. While it is not considered an antidepressant, it does have some effects on the central nervous system that can impact mood.\n\nIt is important to note that while modafinil may be activating, it is not without its own set of potential side effects. These can include headache, nausea, diarrhea, dizziness, and nervousness. In some cases, more serious side effects such as chest pain, shortness of breath, and blackouts have also been reported.\n\nIf you are experiencing symptoms of depression or anxiety, it is important to consult with a healthcare professional to determine the best course of action. They can help you evaluate the potential benefits and risks of using modafinil and determine if it is the right choice for you. HealthChat-LMSYS
       4      user                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      It is activating, but I'm finally doing something. SSRIs or mirtazapine or bupropion did not activate me enough. HealthChat-LMSYS
       5 assistant                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         I'm glad you're feeling more energized and able to do things. It's important to note that activating medications can be helpful for some people, but they may not work for everyone. If you are experiencing improvements in your mood and overall well-being as a result of modafinil, that's great.\n\nHowever, if you are still experiencing symptoms of depression or anxiety, it is important to consult with a healthcare professional to determine if you need additional treatment. They can help you evaluate your symptoms, make a diagnosis, and determine the most appropriate treatment plan.\n\nIt's also important to be aware of the potential side effects of modafinil and to watch for any signs of worsening symptoms. If you notice any concerning changes, it's important to seek medical attention right away.\n\nFinally, it's important to remember that self-medication can be dangerous. Modafinil is a prescription drug that should only be used under the supervision of a healthcare professional. Taking it without a prescription or without consulting with a doctor can potentially be harmful.\n\nI hope this information is helpful. Please let me know if you have any other questions. HealthChat-LMSYS

In [9]:
# Remove rows where the utterance is missing
df_clean = df.dropna(subset=["utterance"]).copy()

print("Original shape:", df.shape)
print("Cleaned shape:", df_clean.shape)

print("\nRemaining missing utterances:")
print(df_clean["utterance"].isna().sum())

Original shape: (276172, 8)
Cleaned shape: (275974, 8)

Remaining missing utterances:
0

In [10]:
# Check for empty or whitespace-only utterances
empty_utterances = df_clean["utterance"].astype(str).str.strip().eq("").sum()

print("Empty/blank utterances:", empty_utterances)

Empty/blank utterances: 0

In [11]:
# Check number of turns per conversation
turns_per_dialogue = df_clean.groupby("dialogue_id").size()

print("Total dialogues:", turns_per_dialogue.shape[0])
print("\nTurn count distribution:")
print(turns_per_dialogue.value_counts().sort_index())

print("\nMinimum turns in a dialogue:", turns_per_dialogue.min())
print("Maximum turns in a dialogue:", turns_per_dialogue.max())

Total dialogues: 123256

Turn count distribution:
1           1
2      118357
3           2
4        1958
5          14
6        1142
7           8
8         518
9          10
10        345
11         16
12        231
13         16
14        152
15         17
16        103
17         10
18         91
19          4
20         60
21          5
22         39
23          1
24         25
25          1
26         21
28         28
30         12
32         11
34          7
36          9
38         10
40          6
42          1
43          1
44          2
46          4
47          1
48          1
50          1
52          1
53          1
54          1
56          1
58          2
60          2
100         7
Name: count, dtype: int64

Minimum turns in a dialogue: 1
Maximum turns in a dialogue: 100

In [12]:
# Check whether speakers alternate correctly within each dialogue

invalid_dialogues = []

for dialogue_id, group in df_clean.groupby("dialogue_id"):
    speakers = group.sort_values("turn_id")["speaker"].tolist()

    for i in range(1, len(speakers)):
        if speakers[i] == speakers[i - 1]:
            invalid_dialogues.append(dialogue_id)
            break

print("Dialogues with consecutive same speakers:", len(set(invalid_dialogues)))

Dialogues with consecutive same speakers: 71

In [14]:
# Check consecutive speakers without looping through every dialogue

df_check = df_clean.sort_values(["dialogue_id", "turn_id"]).copy()

same_as_previous = (
    df_check["speaker"] == df_check.groupby("dialogue_id")["speaker"].shift(1)
)

affected_dialogues = df_check.loc[
    same_as_previous, "dialogue_id"
].unique()

print("Dialogues with consecutive same speakers:", len(affected_dialogues))

Dialogues with consecutive same speakers: 71

In [15]:
# Show the affected dialogues
for dialogue_id in affected_dialogues[:10]:
    temp = df_check[df_check["dialogue_id"] == dialogue_id]

    print("\n" + "=" * 80)
    print("Dialogue ID:", dialogue_id)
    print(temp[["turn_id", "speaker", "utterance", "source_dataset"]].to_string(index=False))

================================================================================
Dialogue ID: 013c533871805e16bda5c173f7719c0a
 turn_id   speaker                                                                                                                                                                                                                                                                                                                                                                                        utterance      source_dataset
       0      user                                                                                                                                                                                                                                                                                                                                        Hydrogen peroxide mouth wash is what type of preparation  HealthChat-WildChat
       1 assistant                                                                                                                                                                                                                                                                                                                                 Hydrogen peroxide mouthwash is a type of antiseptic preparation. HealthChat-WildChat
       3 assistant  As an AI language model, my responses are based on data and algorithms and I do not have personal opinions or beliefs. However, scientifically speaking, hydrogen peroxide has been shown to have antimicrobial properties and can kill bacteria and viruses, which makes it an effective antiseptic agent. When used as a mouthwash, it can help to reduce plaque, gingivitis, and bad breath. HealthChat-WildChat
       4      user                                                                                                                                                                                                                                                                                                                                                     Is hydrogen peroxide mouth wash a solution ? HealthChat-WildChat
       5 assistant Yes, hydrogen peroxide mouthwash is a type of solution. A solution is a homogeneous mixture composed of two or more substances. A solution can be made up of a solute, which is the substance that is dissolved in a solvent, which is the substance that dissolves the solute. In the case of hydrogen peroxide mouthwash, the solute is hydrogen peroxide, while the solvent is usually water. HealthChat-WildChat

================================================================================
Dialogue ID: 0190c13200ac4db0bfcb1a278de1f1a2
 turn_id   speaker                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 utterance   source_dataset
       0      user                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Create a table of contents for a comprehensive Ayurveda book where medical doctors can get a good overview how it aligns with and augments allopathic medicine  HealthChat-LMSYS
       1 assistant                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Sure, here's a table of contents for a comprehensive Ayurveda book that covers how it aligns with and augments allopathic medicine:\n\nI. Introduction to Ayurveda\n\n* History of Ayurveda\n* Basic principles of Ayurveda\n* Comparison of Ayurveda and Allopathic Medicine\n\nII. Ayurvedic Approach to Health and Wellness\n\n* Ayurvedic views on health and disease\n* Ayurvedic diagnosis and treatment methods\n* Ayurvedic practices for maintaining good health\n\nIII. Ayurvedic Treatment for Specific Conditions\n\n* Ayurvedic treatment for common ailments such as headaches, digestive issues, and respiratory problems\n* Ayurvedic treatment for chronic conditions such as diabetes, heart disease, and arthritis\n* Ayurvedic treatment for women's health issues such as menstrual disorders and menopause\n\nIV. Ayurvedic Therapies\n\n* Ayurvedic massage and body treatments\n* Ayurvedic herbal remedies\n* Ayurvedic practices for maintaining a healthy digestive system\n\nV. Allopathic Medicine and Ayurveda\n\n* How Ayurveda complements Allopathic Medicine\n* The role of Ayurveda in preventative care\n* The use of Ayurveda in palliative care\n\nVI. Conclusion\n\n* Summary of key points\n* Future directions for Ayurveda and Allopathic Medicine integration HealthChat-LMSYS
       2      user                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Write about this: Future directions for Ayurveda and Allopathic Medicine integration HealthChat-LMSYS
       3 assistant                                                                                                                                                                         Ayurveda and Allopathic Medicine are two different systems of medicine that have their own unique principles, practices, and approaches to health and wellness. In recent years, there has been growing interest in integrating these two systems of medicine to provide more comprehensive and holistic care to patients.\n\nOne potential direction for integration is through the development of complementary and alternative medicine (CAM) programs that offer Ayurvedic treatments alongside conventional allopathic treatments. This approach allows patients to benefit from the best of both worlds, and can help to reduce the reliance on pharmaceuticals and surgery in some cases.\n\nAnother direction for integration is through research and clinical trials that explore the potential benefits of combining Ayurvedic and allopathic treatments for various conditions. This can help to identify which Ayurvedic interventions are most effective in treating specific health conditions and can help to inform clinical practice.\n\nA third direction for integration is through the training of healthcare professionals in both Ayurveda and Allopathic Medicine. This can help to create a new generation of practitioners who are able to offer patients a more holistic approach to healthcare, and can help to bridge the gap between these two systems of medicine.\n\nUltimately, the integration of Ayurveda and Allopathic Medicine is an evolving field that holds great potential for improving healthcare outcomes and promoting more holistic and sustainable approaches to health and wellness. As research and clinical practice continue to advance, we can expect to see more innovative and effective ways in which these two systems of medicine can be integrated to benefit patients. HealthChat-LMSYS
       4      user                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          How can I integrate Ayurveda into yoga practice  HealthChat-LMSYS
       5 assistant Ayurveda and yoga are two interrelated systems of health and wellness that have their roots in ancient India. Ayurveda is a system of medicine that focuses on promoting health and preventing disease, while yoga is a system of physical, mental, and spiritual practices that aims to unite the body, mind, and spirit.\n\nHere are some ways in which you can integrate Ayurveda into your yoga practice:\n\n1. Use Ayurvedic herbs and supplements: Certain Ayurvedic herbs and supplements, such as ashwagandha and turmeric, have been shown to have beneficial effects on the body and mind. You can incorporate these into your diet or use them as supplements to support your yoga practice.\n2. Incorporate Ayurvedic massage and body treatments: Ayurvedic massage and body treatments, such as abhyanga and shirodhara, can help to relax the body and mind, promote circulation, and support physical and mental well-being.\n3. Practice Ayurvedic cleansing and detoxification techniques: Ayurveda emphasizes the importance of cleansing and detoxification to maintain optimal health. You can incorporate Ayurvedic techniques, such as panchakarma, into your practice to support your overall health and well-being.\n4. Incorporate Ayurvedic breathing and relaxation techniques: Ayurveda places a strong emphasis on breathing and relaxation techniques, such as pranayama and shavasana, to support physical and mental health. You can incorporate these techniques into your yoga practice to enhance your overall experience.\n5. Consider Ayurveda in your yoga practice: As you practice yoga, you can think about how the principles of Ayurveda can support your practice. For example, you can focus on the principles of balance and harmony, and use yoga to support your overall health and well-being.\n\nBy integrating Ayurveda into your yoga practice, you can enhance your overall experience and support your physical, mental, and spiritual well-being. HealthChat-LMSYS
       6      user                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          What is the sentiment score for  HealthChat-LMSYS

In [16]:
# Check for gaps in turn IDs within each dialogue

turn_counts = (
    df_clean.groupby("dialogue_id")["turn_id"]
    .agg(["min", "max", "count"])
)

turn_counts["expected_count"] = (
    turn_counts["max"] - turn_counts["min"] + 1
)

gapped_dialogues = turn_counts[
    turn_counts["count"] != turn_counts["expected_count"]
]

print("Dialogues with turn_id gaps:", len(gapped_dialogues))
print("Total dialogues:", len(turn_counts))

Dialogues with turn_id gaps: 71
Total dialogues: 123256

In [17]:
# Create the final master dataset for NLU preparation

df_master = df_clean.copy()

print("Master dataset shape:", df_master.shape)
print("Missing utterances:", df_master["utterance"].isna().sum())
print("Empty utterances:",
      df_master["utterance"].astype(str).str.strip().eq("").sum())

Master dataset shape: (275974, 8)
Missing utterances: 0
Empty utterances: 0

In [18]:
# Basic text statistics for NLU preparation

df_master["text_length"] = df_master["utterance"].astype(str).str.len()

print("Average characters:", round(df_master["text_length"].mean(), 2))
print("Median characters:", df_master["text_length"].median())
print("Maximum characters:", df_master["text_length"].max())

print("\nTurns by speaker:")
print(df_master["speaker"].value_counts())

print("\nTurns by source:")
print(df_master["source_dataset"].value_counts())

Average characters: 578.18
Median characters: 479.0
Maximum characters: 40404

Turns by speaker:
speaker
user         138037
assistant    137937
Name: count, dtype: int64

Turns by source:
source_dataset
MedDialog              224328
HealthChat-LMSYS        28465
HealthChat-WildChat     23181
Name: count, dtype: int64

In [19]:
# Check how many utterances are very long

for limit in [1000, 2000, 4000, 8000, 16000]:
    count = (df_master["text_length"] > limit).sum()
    print(f"Utterances longer than {limit} characters: {count}")

Utterances longer than 1000 characters: 28050
Utterances longer than 2000 characters: 5371
Utterances longer than 4000 characters: 297
Utterances longer than 8000 characters: 29
Utterances longer than 16000 characters: 9

In [20]:
# Remove the temporary text_length column

df_master = df_master.drop(columns=["text_length"])

print("Columns:")
print(df_master.columns.tolist())

print("\nShape:", df_master.shape)

Columns:
['dialogue_id', 'turn_id', 'speaker', 'utterance', 'source_dataset', 'original_id', 'source_label_raw', 'dialogue_origin']

Shape: (275974, 8)

In [22]:
# Display one complete conversation

sample_dialogue_id = df_master["dialogue_id"].iloc[0]

sample = (
    df_master[df_master["dialogue_id"] == sample_dialogue_id]
    .sort_values("turn_id")
)

print("Dialogue ID:", sample_dialogue_id)
print("Number of turns:", len(sample))

for _, row in sample.iterrows():
    print(f"\n{row['speaker'].upper()}:")
    print(row["utterance"])

Dialogue ID: 000573958699464e9de6493b5e182fab
Number of turns: 10

USER:
Prompt: I want you to be my personal mental health Al counselor. I am a 16 year old male, struggling with OCD. Let's have a counseling session. I want you to utilize evidence-based therapeutic techniques to guide me through my struggles and help me improve my mental health.  Remember we are having a chat -- don't overwhelm me with a lot of text and keep the conversation flowing. Input: "Hey there, I'm NAME_1"

ASSISTANT:
NAME_2, it's nice to meet you. I'm here to help you with your mental health, specifically with your OCD. Let's start by talking about what you're currently experiencing with your OCD. What are some of the thoughts or behaviors that are causing you distress?

USER:
I guess there's quite a few things. But I primarily struggle with cleanliness

ASSISTANT:
Okay, that's a common theme for many people with OCD. Can you tell me more about what you do to try and maintain cleanliness? Are there certain things or situations that trigger your OCD thoughts and behaviors?

USER:
Yeah, for example today I worked out in the morning and wanted to wash my hands after. But I didn't feel like they were clean enough. So I rewashed them over 15 times over the span of an hour, until my skin was completely dry.

ASSISTANT:
I see. It sounds like you're experiencing excessive hand-washing, which is a common symptom of OCD. It can be difficult to control these compulsions, but there are ways to manage them. One technique that may be helpful for you is called "stimulus control." It involves breaking the connection between the trigger and the compulsive behavior.

For example, you can set a timer for hand-washing and only wash your hands for a certain amount of time, or you can use a specific type of soap that you only use for washing your hands. By breaking the connection between the trigger (dirt or discomfort) and the compulsive behavior (excessive washing), you can gradually weaken the OCD symptoms.

Do you think this technique might be helpful for you? Are there any other compulsions or thoughts that are causing you distress?

USER:
How do I motivate myself to do this? I see how it'd help, but I feel like I wouldn't be able to mentally handle it

ASSISTANT:
It's understandable that it can be difficult to motivate yourself to change old habits and patterns, especially when they are deeply ingrained. But remember, you are not alone and many people have successfully managed their OCD with the help of evidence-based therapies.

One way to motivate yourself is to focus on the benefits of making changes. For example, by reducing your hand-washing, you may be able to save time, prevent skin irritation, and reduce your anxiety. It can also be helpful to set small, achievable goals for yourself and reward yourself when you meet them.

Another technique that may be helpful is called "cognitive restructuring." This involves identifying and challenging negative or distorted thoughts, such as the belief that you need to wash your hands a certain number of times to be clean. By challenging these thoughts and replacing them with more realistic and positive ones, you can reduce your anxiety and improve your overall well-being.

Would you like to try these techniques and see if they can help you manage your OCD symptoms?

USER:
Can you tell me a little more about how I can implement cognitive restructuring?

ASSISTANT:
Sure, cognitive restructuring is a technique that can help you identify and challenge negative or distorted thoughts, and replace them with more positive and realistic ones. Here are some steps you can follow:

1. Identify the negative thought or belief: The first step is to identify the negative thought or belief that's causing you distress. For example, you may believe that you need to wash your hands a certain number of times to be clean.
2. Challenge the thought: Once you've identified the negative thought, the next step is to challenge it. Ask yourself if it's really true, or if there's any evidence to support it. In this case, you might ask yourself if washing your hands 15 times is really necessary to be clean.
3. Replace the thought: Once you've challenged the negative thought, try to replace it with a more positive and realistic one. For example, you could remind yourself that washing your hands a few times is enough to keep them clean and healthy.
4. Practice: Like any skill, cognitive restructuring takes practice. Try to focus on your thoughts and beliefs throughout the day, and try to challenge any negative or distorted thoughts you notice. Over time, you'll become better at identifying and changing these thoughts, which can help you reduce your anxiety and improve your overall well-being.

Remember, it's important to be patient with yourself and not get discouraged if you don't see immediate results. Change takes time and practice, but with persistence, you can make progress and improve your mental health.

In [23]:
# Count dialogues by source dataset

dialogue_sources = (
    df_master.groupby(["dialogue_id", "source_dataset"])
    .size()
    .reset_index(name="turn_count")
)

print(dialogue_sources["source_dataset"].value_counts())

print("\nNumber of dialogues by source:")
print(
    dialogue_sources
    .groupby("source_dataset")["dialogue_id"]
    .nunique()
)

source_dataset
MedDialog              112164
HealthChat-LMSYS         6828
HealthChat-WildChat      4264
Name: count, dtype: int64

Number of dialogues by source:
source_dataset
HealthChat-LMSYS         6828
HealthChat-WildChat      4264
MedDialog              112164
Name: dialogue_id, dtype: int64

In [24]:
# Inspect the available labels in the cleaned dataset

print("Total non-null source labels:",
      df_master["source_label_raw"].notna().sum())

print("\nUnique source labels:")
print(df_master["source_label_raw"].dropna().value_counts().head(30))

print("\nNumber of unique labels:",
      df_master["source_label_raw"].nunique())

Total non-null source labels: 224328

Unique source labels:
source_label_raw
If you are a doctor, please answer the medical questions based on the patient's description.    224328
Name: count, dtype: int64

Number of unique labels: 1

In [25]:
# Create conversation-level training examples

def build_conversation(group):
    group = group.sort_values("turn_id")

    conversation = []

    for _, row in group.iterrows():
        speaker = row["speaker"].capitalize()
        utterance = str(row["utterance"]).strip()

        conversation.append(f"{speaker}: {utterance}")

    return "\n".join(conversation)


df_conversations = (
    df_master
    .groupby("dialogue_id", sort=False)
    .apply(build_conversation)
    .reset_index(name="text")
)

print("Conversation dataset shape:", df_conversations.shape)

print("\nColumns:")
print(df_conversations.columns.tolist())

print("\nFirst conversation:")
print(df_conversations.iloc[0]["text"])

Conversation dataset shape: (123256, 2)

Columns:
['dialogue_id', 'text']

First conversation:
User: Prompt: I want you to be my personal mental health Al counselor. I am a 16 year old male, struggling with OCD. Let's have a counseling session. I want you to utilize evidence-based therapeutic techniques to guide me through my struggles and help me improve my mental health.  Remember we are having a chat -- don't overwhelm me with a lot of text and keep the conversation flowing. Input: "Hey there, I'm NAME_1"
Assistant: NAME_2, it's nice to meet you. I'm here to help you with your mental health, specifically with your OCD. Let's start by talking about what you're currently experiencing with your OCD. What are some of the thoughts or behaviors that are causing you distress?
User: I guess there's quite a few things. But I primarily struggle with cleanliness
Assistant: Okay, that's a common theme for many people with OCD. Can you tell me more about what you do to try and maintain cleanliness? Are there certain things or situations that trigger your OCD thoughts and behaviors?
User: Yeah, for example today I worked out in the morning and wanted to wash my hands after. But I didn't feel like they were clean enough. So I rewashed them over 15 times over the span of an hour, until my skin was completely dry.
Assistant: I see. It sounds like you're experiencing excessive hand-washing, which is a common symptom of OCD. It can be difficult to control these compulsions, but there are ways to manage them. One technique that may be helpful for you is called "stimulus control." It involves breaking the connection between the trigger and the compulsive behavior.

For example, you can set a timer for hand-washing and only wash your hands for a certain amount of time, or you can use a specific type of soap that you only use for washing your hands. By breaking the connection between the trigger (dirt or discomfort) and the compulsive behavior (excessive washing), you can gradually weaken the OCD symptoms.

Do you think this technique might be helpful for you? Are there any other compulsions or thoughts that are causing you distress?
User: How do I motivate myself to do this? I see how it'd help, but I feel like I wouldn't be able to mentally handle it
Assistant: It's understandable that it can be difficult to motivate yourself to change old habits and patterns, especially when they are deeply ingrained. But remember, you are not alone and many people have successfully managed their OCD with the help of evidence-based therapies.

One way to motivate yourself is to focus on the benefits of making changes. For example, by reducing your hand-washing, you may be able to save time, prevent skin irritation, and reduce your anxiety. It can also be helpful to set small, achievable goals for yourself and reward yourself when you meet them.

Another technique that may be helpful is called "cognitive restructuring." This involves identifying and challenging negative or distorted thoughts, such as the belief that you need to wash your hands a certain number of times to be clean. By challenging these thoughts and replacing them with more realistic and positive ones, you can reduce your anxiety and improve your overall well-being.

Would you like to try these techniques and see if they can help you manage your OCD symptoms?
User: Can you tell me a little more about how I can implement cognitive restructuring?
Assistant: Sure, cognitive restructuring is a technique that can help you identify and challenge negative or distorted thoughts, and replace them with more positive and realistic ones. Here are some steps you can follow:

1. Identify the negative thought or belief: The first step is to identify the negative thought or belief that's causing you distress. For example, you may believe that you need to wash your hands a certain number of times to be clean.
2. Challenge the thought: Once you've identified the negative thought, the next step is to challenge it. Ask yourself if it's really true, or if there's any evidence to support it. In this case, you might ask yourself if washing your hands 15 times is really necessary to be clean.
3. Replace the thought: Once you've challenged the negative thought, try to replace it with a more positive and realistic one. For example, you could remind yourself that washing your hands a few times is enough to keep them clean and healthy.
4. Practice: Like any skill, cognitive restructuring takes practice. Try to focus on your thoughts and beliefs throughout the day, and try to challenge any negative or distorted thoughts you notice. Over time, you'll become better at identifying and changing these thoughts, which can help you reduce your anxiety and improve your overall well-being.

Remember, it's important to be patient with yourself and not get discouraged if you don't see immediate results. Change takes time and practice, but with persistence, you can make progress and improve your mental health.

/tmp/ipykernel_58/2957407992.py:20: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(build_conversation)

In [26]:
# Recreate conversation dataset without the pandas warning

df_conversations = (
    df_master
    .groupby("dialogue_id", sort=False)[["dialogue_id", "turn_id", "speaker", "utterance"]]
    .apply(
        lambda group: "\n".join(
            f"{row['speaker'].capitalize()}: {str(row['utterance']).strip()}"
            for _, row in group.sort_values("turn_id").iterrows()
        )
    )
    .reset_index(name="text")
)

print("Conversation dataset shape:", df_conversations.shape)

print("\nMissing conversations:")
print(df_conversations["text"].isna().sum())

print("\nFirst conversation preview:")
print(df_conversations.iloc[0]["text"][:1000])

Conversation dataset shape: (123256, 2)

Missing conversations:
0

First conversation preview:
User: Prompt: I want you to be my personal mental health Al counselor. I am a 16 year old male, struggling with OCD. Let's have a counseling session. I want you to utilize evidence-based therapeutic techniques to guide me through my struggles and help me improve my mental health.  Remember we are having a chat -- don't overwhelm me with a lot of text and keep the conversation flowing. Input: "Hey there, I'm NAME_1"
Assistant: NAME_2, it's nice to meet you. I'm here to help you with your mental health, specifically with your OCD. Let's start by talking about what you're currently experiencing with your OCD. What are some of the thoughts or behaviors that are causing you distress?
User: I guess there's quite a few things. But I primarily struggle with cleanliness
Assistant: Okay, that's a common theme for many people with OCD. Can you tell me more about what you do to try and maintain cleanliness? Are there certain things or situations that trigger your OCD thoughts and behaviors?
User:

In [27]:
from sklearn.model_selection import train_test_split

# Split at conversation level
train_df, val_df = train_test_split(
    df_conversations,
    test_size=0.10,
    random_state=42,
    shuffle=True
)

# Reset indices
train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)

print("Training conversations:", len(train_df))
print("Validation conversations:", len(val_df))

print("\nTraining percentage:",
      round(len(train_df) / len(df_conversations) * 100, 2), "%")

print("Validation percentage:",
      round(len(val_df) / len(df_conversations) * 100, 2), "%")

Training conversations: 110930
Validation conversations: 12326

Training percentage: 90.0 %
Validation percentage: 10.0 %

In [28]:
# Verify that no dialogue appears in both train and validation

train_ids = set(train_df["dialogue_id"])
val_ids = set(val_df["dialogue_id"])

overlap = train_ids.intersection(val_ids)

print("Training dialogue IDs:", len(train_ids))
print("Validation dialogue IDs:", len(val_ids))
print("Overlapping dialogue IDs:", len(overlap))

Training dialogue IDs: 110930
Validation dialogue IDs: 12326
Overlapping dialogue IDs: 0

In [29]:
!pip install -q -U transformers datasets accelerate peft bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 77.4 MB/s eta 0:00:00:00:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 26.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 389.2/389.2 kB 19.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 775.8/775.8 kB 31.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 38.0 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 516.0/516.0 kB 23.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 78.1 MB/s eta 0:00:00:00:01

In [30]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("GPU memory:", round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2), "GB")
else:
    print("⚠️ No GPU detected")

PyTorch version: 2.10.0+cpu
CUDA available: False
⚠️ No GPU detected

In [1]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("GPU memory:", round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2), "GB")
else:
    print("⚠️ No GPU detected")

PyTorch version: 2.10.0+cu128
CUDA available: True
GPU: Tesla T4
GPU memory: 14.56 GB

In [2]:
import transformers
import datasets
import peft
import accelerate
import bitsandbytes

print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)
print("PEFT:", peft.__version__)
print("Accelerate:", accelerate.__version__)
print("BitsAndBytes:", bitsandbytes.__version__)

ModuleNotFoundError: No module named 'bitsandbytes'

In [4]:
!pip install -q -U bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 37.7 MB/s eta 0:00:00:00:0100:01

In [5]:
import bitsandbytes as bnb

print("bitsandbytes:", bnb.__version__)

bitsandbytes: 0.50.2

In [6]:
from transformers import AutoTokenizer

model_name = "BioMistral/BioMistral-7B"

tokenizer = AutoTokenizer.from_pretrained(model_name)

print("Tokenizer loaded successfully!")
print("Vocabulary size:", len(tokenizer))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/567 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/72.0 [00:00<?, ?B/s]

Tokenizer loaded successfully!
Vocabulary size: 32000

In [7]:
# Tokenize a sample of our training conversations

sample_texts = train_df["text"].sample(
    n=min(1000, len(train_df)),
    random_state=42
).tolist()

token_lengths = [
    len(tokenizer(text, add_special_tokens=True)["input_ids"])
    for text in sample_texts
]

import numpy as np

print("Number of conversations checked:", len(token_lengths))
print("Minimum tokens:", min(token_lengths))
print("Median tokens:", int(np.median(token_lengths)))
print("Average tokens:", int(np.mean(token_lengths)))
print("90th percentile:", int(np.percentile(token_lengths, 90)))
print("95th percentile:", int(np.percentile(token_lengths, 95)))
print("Maximum tokens:", max(token_lengths))

NameError: name 'train_df' is not defined

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split

file_path = "/kaggle/input/datasets/shilpadevi1527/integrated-conversations-csv/integrated_conversations.csv"

# Load dataset
df = pd.read_csv(file_path)

# Remove rows with missing utterances
df_master = df.dropna(subset=["utterance"]).copy()

# Build one conversation per dialogue
df_conversations = (
    df_master
    .groupby("dialogue_id", sort=False)[
        ["dialogue_id", "turn_id", "speaker", "utterance"]
    ]
    .apply(
        lambda group: "\n".join(
            f"{row['speaker'].capitalize()}: {str(row['utterance']).strip()}"
            for _, row in group.sort_values("turn_id").iterrows()
        )
    )
    .reset_index(name="text")
)

# Same 90/10 split as before
train_df, val_df = train_test_split(
    df_conversations,
    test_size=0.10,
    random_state=42,
    shuffle=True
)

train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)

print("Total conversations:", len(df_conversations))
print("Training conversations:", len(train_df))
print("Validation conversations:", len(val_df))

Total conversations: 123256
Training conversations: 110930
Validation conversations: 12326

In [15]:
import numpy as np

sample_texts = train_df["text"].sample(
    n=min(1000, len(train_df)),
    random_state=42
).tolist()

token_lengths = [
    len(tokenizer(text, add_special_tokens=True)["input_ids"])
    for text in sample_texts
]

print("Number of conversations checked:", len(token_lengths))
print("Minimum tokens:", min(token_lengths))
print("Median tokens:", int(np.median(token_lengths)))
print("Average tokens:", int(np.mean(token_lengths)))
print("90th percentile:", int(np.percentile(token_lengths, 90)))
print("95th percentile:", int(np.percentile(token_lengths, 95)))
print("Maximum tokens:", max(token_lengths))

Number of conversations checked: 1000
Minimum tokens: 128
Median tokens: 258
Average tokens: 315
90th percentile: 410
95th percentile: 495
Maximum tokens: 4776

In [16]:
from datasets import Dataset

# Keep only the conversation text
train_dataset = Dataset.from_pandas(
    train_df[["text"]],
    preserve_index=False
)

val_dataset = Dataset.from_pandas(
    val_df[["text"]],
    preserve_index=False
)

print("Training dataset:", train_dataset)
print("Validation dataset:", val_dataset)

print("\nExample:")
print(train_dataset[0]["text"][:500])

Training dataset: Dataset({
    features: ['text'],
    num_rows: 110930
})
Validation dataset: Dataset({
    features: ['text'],
    num_rows: 12326
})

Example:
User: What are the effects of the drug buspirone and how does it work biologically?
Assistant: Buspirone is a medication that is primarily used to treat anxiety disorders. It works by modulating the activity of neurotransmitters in the brain, specifically serotonin and dopamine. Buspirone acts as a serotonin 1A receptor agonist, which means that it binds to and stimulates these receptors, leading to an increase in the levels of serotonin in the brain. This increased serotonin activity can help t

In [17]:
MAX_LENGTH = 512

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=MAX_LENGTH,
        padding=False
    )

train_tokenized = train_dataset.map(
    tokenize_function,
    batched=True,
    remove_columns=["text"],
    desc="Tokenizing training data"
)

val_tokenized = val_dataset.map(
    tokenize_function,
    batched=True,
    remove_columns=["text"],
    desc="Tokenizing validation data"
)

print("Training tokenized:", train_tokenized)
print("Validation tokenized:", val_tokenized)

Tokenizing training data:   0%|          | 0/110930 [00:00<?, ? examples/s]

Tokenizing validation data:   0%|          | 0/12326 [00:00<?, ? examples/s]

Training tokenized: Dataset({
    features: ['input_ids', 'attention_mask'],
    num_rows: 110930
})
Validation tokenized: Dataset({
    features: ['input_ids', 'attention_mask'],
    num_rows: 12326
})

In [18]:
print("Number of tokens:", len(train_tokenized[0]["input_ids"]))
print("Number of attention values:", len(train_tokenized[0]["attention_mask"]))

print("\nFirst 20 token IDs:")
print(train_tokenized[0]["input_ids"][:20])

print("\nAttention mask:")
print(train_tokenized[0]["attention_mask"][:20])

Number of tokens: 287
Number of attention values: 287

First 20 token IDs:
[1, 1247, 28747, 1824, 460, 272, 6092, 302, 272, 7876, 1579, 28720, 361, 538, 304, 910, 1235, 378, 771, 4240]

Attention mask:
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [19]:
import torch
from transformers import AutoModelForCausalLM, BitsAndBytesConfig

model_name = "BioMistral/BioMistral-7B"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

print("BioMistral-7B loaded successfully!")
print("Model device:", model.device)

pytorch_model.bin:   0%|          | 0.00/14.5G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Error during conversion: ReadTimeout('The read operation timed out')
Exception in thread Thread-auto_conversion:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/transformers/safetensors_conversion.py", line 116, in auto_conversion
    raise e
  File "/usr/local/lib/python3.12/dist-packages/transformers/safetensors_conversion.py", line 95, in auto_conversion
    sha = get_conversion_pr_reference(api, pretrained_model_name_or_path, **cached_file_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/safetensors_conversion.py", line 76, in get_conversion_pr_reference
    raise OSError(
OSError: Could not create safetensors conversion PR. The repo does not appear to have a file named pytorch_model.bin or model.safetensors.If you are loading with variant, use `use_safetensors=False` to load the original model.

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

BioMistral-7B loaded successfully!
Model device: cuda:0

In [20]:
from peft import prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model)

print("Model prepared for QLoRA training!")

Model prepared for QLoRA training!

In [21]:
from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj"
    ]
)

model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

trainable params: 13,631,488 || all params: 7,255,363,584 || trainable%: 0.1879

In [22]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./biomistral_qlora",
    
    num_train_epochs=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=16,
    
    learning_rate=2e-4,
    weight_decay=0.01,
    
    fp16=True,
    gradient_checkpointing=True,
    
    logging_steps=50,
    eval_strategy="steps",
    eval_steps=500,
    save_strategy="steps",
    save_steps=500,
    save_total_limit=2,
    
    report_to="none",
    optim="paged_adamw_8bit",
    
    remove_unused_columns=False
)

print("Training configuration created successfully!")

Training configuration created successfully!

In [23]:
from transformers import DataCollatorForLanguageModeling

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

print("Data collator created successfully!")

Data collator created successfully!

In [24]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,
    data_collator=data_collator,
)

print("Trainer created successfully!")

Trainer created successfully!

In [25]:
import torch

print("GPU:", torch.cuda.get_device_name(0))
print("GPU memory before training:",
      round(torch.cuda.memory_allocated() / 1024**3, 2), "GB")

# Temporarily train on only 10 examples
test_trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized.select(range(10)),
    data_collator=data_collator,
)

test_result = test_trainer.train()

print("\nSanity-check training completed!")
print("Training loss:", test_result.training_loss)

print("GPU memory after training:",
      round(torch.cuda.memory_allocated() / 1024**3, 2), "GB")

GPU: Tesla T4
GPU memory before training: 1.77 GB

ValueError: You have set `args.eval_strategy` to IntervalStrategy.STEPS but you didn't pass an `eval_dataset` to `Trainer`. Either set `args.eval_strategy` to `no` or pass an `eval_dataset`.

In [26]:
import torch
from transformers import TrainingArguments, Trainer

test_args = TrainingArguments(
    output_dir="./biomistral_test",
    max_steps=10,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    fp16=True,
    gradient_checkpointing=True,
    logging_steps=1,
    eval_strategy="no",
    save_strategy="no",
    report_to="none",
    optim="paged_adamw_8bit",
    remove_unused_columns=False
)

test_trainer = Trainer(
    model=model,
    args=test_args,
    train_dataset=train_tokenized.select(range(10)),
    data_collator=data_collator,
)

print("Starting 10-step sanity check...")

test_result = test_trainer.train()

print("\nSanity-check training completed!")
print("Training loss:", test_result.training_loss)

print(
    "GPU memory after training:",
    round(torch.cuda.memory_allocated() / 1024**3, 2),
    "GB"
)

Starting 10-step sanity check...

ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.

In [27]:
tokenizer.pad_token = tokenizer.eos_token

print("PAD token:", tokenizer.pad_token)
print("PAD token ID:", tokenizer.pad_token_id)
print("EOS token:", tokenizer.eos_token)
print("EOS token ID:", tokenizer.eos_token_id)

PAD token: </s>
PAD token ID: 2
EOS token: </s>
EOS token ID: 2

In [28]:
from transformers import DataCollatorForLanguageModeling

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

print("Data collator updated successfully!")

Data collator updated successfully!

In [29]:
import torch
from transformers import TrainingArguments, Trainer

test_args = TrainingArguments(
    output_dir="./biomistral_test",
    max_steps=10,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    fp16=True,
    gradient_checkpointing=True,
    logging_steps=1,
    eval_strategy="no",
    save_strategy="no",
    report_to="none",
    optim="paged_adamw_8bit",
    remove_unused_columns=False
)

test_trainer = Trainer(
    model=model,
    args=test_args,
    train_dataset=train_tokenized.select(range(10)),
    data_collator=data_collator,
)

print("Starting 10-step sanity check...")

test_result = test_trainer.train()

print("\nSanity-check training completed!")
print("Training loss:", test_result.training_loss)

print(
    "GPU memory after training:",
    round(torch.cuda.memory_allocated() / 1024**3, 2),
    "GB"
)

Starting 10-step sanity check...

Sanity-check training completed!
Training loss: 2.5556390225887298
GPU memory after training: 1.79 GB

In [30]:
import gc
import torch

del test_trainer
del test_result

gc.collect()
torch.cuda.empty_cache()

print("Temporary test trainer cleared.")
print(
    "GPU memory currently allocated:",
    round(torch.cuda.memory_allocated() / 1024**3, 2),
    "GB"
)

Temporary test trainer cleared.
GPU memory currently allocated: 1.78 GB

In [31]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,
    data_collator=data_collator,
)

print("Real Trainer recreated successfully!")
print("Training examples:", len(train_tokenized))
print("Validation examples:", len(val_tokenized))

Real Trainer recreated successfully!
Training examples: 110930
Validation examples: 12326

In [32]:
print("Starting BioMistral-7B QLoRA training...")
print("Training examples:", len(train_tokenized))
print("Validation examples:", len(val_tokenized))

train_result = trainer.train()

print("\nTraining completed!")
print("Final training loss:", train_result.training_loss)

Starting BioMistral-7B QLoRA training...
Training examples: 110930
Validation examples: 12326

KeyboardInterrupt:

In [33]:
# Use a reproducible 20,000-conversation subset
TRAIN_SIZE = 20_000

train_small = train_tokenized.shuffle(seed=42).select(range(TRAIN_SIZE))

print("Training examples:", len(train_small))
print("Validation examples:", len(val_tokenized))

Training examples: 20000
Validation examples: 12326

In [35]:
from transformers import TrainingArguments

training_args_small = TrainingArguments(
    output_dir="./biomistral_qlora_20k",

    num_train_epochs=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,

    learning_rate=2e-4,
    weight_decay=0.01,

    fp16=True,
    gradient_checkpointing=True,

    logging_steps=25,

    eval_strategy="steps",
    eval_steps=1000,

    save_strategy="steps",
    save_steps=1000,
    save_total_limit=2,

    report_to="none",
    optim="paged_adamw_8bit",

    remove_unused_columns=False
)

print("20K training configuration created!")

20K training configuration created!

In [36]:
from transformers import Trainer

trainer_small = Trainer(
    model=model,
    args=training_args_small,
    train_dataset=train_small,
    eval_dataset=val_tokenized,
    data_collator=data_collator,
)

print("20K Trainer created successfully!")
print("Training examples:", len(train_small))
print("Validation examples:", len(val_tokenized))

20K Trainer created successfully!
Training examples: 20000
Validation examples: 12326

In [37]:
import time

speed_args = TrainingArguments(
    output_dir="./biomistral_speed_test",
    max_steps=100,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,

    fp16=True,
    gradient_checkpointing=True,

    logging_steps=25,
    eval_strategy="no",
    save_strategy="no",

    report_to="none",
    optim="paged_adamw_8bit",
    remove_unused_columns=False
)

speed_trainer = Trainer(
    model=model,
    args=speed_args,
    train_dataset=train_small,
    data_collator=data_collator,
)

print("Starting 100-step speed test...")
start_time = time.time()

speed_result = speed_trainer.train()

elapsed = time.time() - start_time

print("\n100-step test completed!")
print("Time taken:", round(elapsed / 60, 2), "minutes")
print("Average time per step:", round(elapsed / 100, 2), "seconds")
print("Training loss:", speed_result.training_loss)

Starting 100-step speed test...

CheckpointError: torch.utils.checkpoint: A different number of tensors was saved during the original forward and recomputation.
Number of tensors saved during forward: 86
Number of tensors saved during recomputation: 42.

Tip: To see a more detailed error message, either pass `debug=True` to
`torch.utils.checkpoint.checkpoint(...)` or wrap the code block
with `with torch.utils.checkpoint.set_checkpoint_debug_enabled(True):` to
enable checkpoint‑debug mode globally.

In [38]:
# Disable gradient checkpointing to avoid the PyTorch checkpoint recomputation error

model.gradient_checkpointing_disable()

print("Gradient checkpointing:", model.is_gradient_checkpointing)

Gradient checkpointing: False

In [39]:
import time
from transformers import TrainingArguments, Trainer

speed_args = TrainingArguments(
    output_dir="./biomistral_speed_test",
    max_steps=100,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,

    fp16=True,
    gradient_checkpointing=False,

    logging_steps=25,
    eval_strategy="no",
    save_strategy="no",

    report_to="none",
    optim="paged_adamw_8bit",
    remove_unused_columns=False
)

speed_trainer = Trainer(
    model=model,
    args=speed_args,
    train_dataset=train_small,
    data_collator=data_collator,
)

print("Starting 100-step speed test...")
start_time = time.time()

speed_result = speed_trainer.train()

elapsed = time.time() - start_time

print("\n100-step test completed!")
print("Time taken:", round(elapsed / 60, 2), "minutes")
print("Average time per step:", round(elapsed / 100, 2), "seconds")
print("Training loss:", speed_result.training_loss)

Starting 100-step speed test...

100-step test completed!
Time taken: 15.69 minutes
Average time per step: 9.42 seconds
Training loss: 2.2317174911499023

In [40]:
from transformers import TrainingArguments

final_args = TrainingArguments(
    output_dir="./biomistral_qlora_20k",

    num_train_epochs=1,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,

    learning_rate=2e-4,
    weight_decay=0.01,

    fp16=True,
    gradient_checkpointing=False,

    logging_steps=100,

    eval_strategy="no",

    save_strategy="epoch",
    save_total_limit=1,

    report_to="none",
    optim="paged_adamw_8bit",

    remove_unused_columns=False
)

print("Final 20K training configuration ready!")

Final 20K training configuration ready!

In [41]:
from transformers import Trainer

final_trainer = Trainer(
    model=model,
    args=final_args,
    train_dataset=train_small,
    eval_dataset=val_tokenized,
    data_collator=data_collator,
)

print("Final Trainer created successfully!")
print("Training examples:", len(train_small))
print("Validation examples:", len(val_tokenized))

Final Trainer created successfully!
Training examples: 20000
Validation examples: 12326

In [43]:
print("🚀 Starting BioMistral-7B QLoRA training on 20,000 conversations...")
print("Training examples:", len(train_small))

train_result = final_trainer.train()

print("\n✅ Training completed!")
print("Final training loss:", train_result.training_loss)

🚀 Starting BioMistral-7B QLoRA training on 20,000 conversations...
Training examples: 20000

KeyboardInterrupt:

In [44]:
print("Model:", model_name)
print("Model loaded on:", model.device)
print("Parameters:", sum(p.numel() for p in model.parameters()))
print("LoRA attached:", hasattr(model, "peft_config"))

Model: BioMistral/BioMistral-7B
Model loaded on: cuda:0
Parameters: 3765702656
LoRA attached: True

In [45]:
model = model.unload()

print("LoRA removed successfully!")
print("Model:", model_name)
print("Device:", model.device)

LoRA removed successfully!
Model: BioMistral/BioMistral-7B
Device: cuda:0

In [47]:
import torch

question = "What are the common symptoms of iron deficiency anemia?"

prompt = f"User: {question}\nAssistant:"

inputs = tokenizer(
    prompt,
    return_tensors="pt"
).to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=100,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )

response = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print("INPUT:")
print(question)

print("\nMODEL OUTPUT:")
print(response)

INPUT:
What are the common symptoms of iron deficiency anemia?

MODEL OUTPUT:
User: What are the common symptoms of iron deficiency anemia?
Assistant: The common symptoms of iron deficiency anemia include fatigue, weakness, paleness, shortness of breath, chest pain, dizziness, headaches, cold extremities, and dark circles under the eyes.